[package]
name = "bramble-git-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octocrab = "0.32.0"
serde_yaml = "0.9.30"
tokio = {version = "1.35.1", features = ["full"]}
