# permissions for end users to edit executions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: execution-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: execution-editor-role
rules:
  - apiGroups:
      - pipelines.bramble.dev
    resources:
      - executions
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - pipelines.bramble.dev
    resources:
      - executions/status
    verbs:
      - get
      - update
