- git-repo:
    provider: github
    owner: coillteoir
    repo: bramble
  branch-rules:
    - branch-pattern: ^master$|^main$
      pipeline: bramble-release
    - branch-pattern: develop
      pipeline: bramble-dev
