---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
      - persistentvolumes
      - pods
    verbs:
      - create
      - delete
      - get
      - list
  - apiGroups:
      - pipelines.bramble.dev
    resources:
      - executions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - pipelines.bramble.dev
    resources:
      - executions/finalizers
    verbs:
      - update
  - apiGroups:
      - pipelines.bramble.dev
    resources:
      - executions/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - pipelines.bramble.dev
    resources:
      - pipelines
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - pipelines.bramble.dev
    resources:
      - pipelines/finalizers
    verbs:
      - update
  - apiGroups:
      - pipelines.bramble.dev
    resources:
      - pipelines/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - pipelines.bramble.dev
    resources:
      - tasks
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - pipelines.bramble.dev
    resources:
      - tasks/finalizers
    verbs:
      - update
  - apiGroups:
      - pipelines.bramble.dev
    resources:
      - tasks/status
    verbs:
      - get
      - patch
      - update
