apiVersion: pipelines.bramble.dev/v1alpha1
kind: Pipeline
metadata:
  name: cbuild
spec:
  tasks:
    - name: compile
      spec:
        image: gcc
        command:
          ["gcc"
          ,"-Wall"
          ,"-Wextra"
          ,"-Werror"
          ,"-o"
          ,"/src/ctml"
          ,"/src/src/main.c"]
        dependencies:
          - check
          - test
    - name: check
      spec:
        image: ghcr.io/facthunder/cppcheck:latest
        command:
          - "true"
        dependencies:
        - format
    - name: format
      spec:
        image: ubuntu
        command: ["astyle", "--diff", "."]
    - name: test
      spec:
        image: ninja
        command: ["ninja", "test", "/src/"]
