apiVersion: pipelines.bramble.dev/v1alpha1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/name: pipeline
    app.kubernetes.io/instance: pipeline-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: build
spec:
  tasks:
    - name: build
      spec:
        image: golang:latest
        command: ["GOOS=linux", "GOARCH=amd64", "go", "build", "-o", "main"]
      dependencies: ["hello"]
  taskRefs:
    - name: docker-build
      dependencies: ["build"]
