apiVersion: pipelines.lugh.dev/v1alpha1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/name: pipeline
    app.kubernetes.io/instance: pipeline-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: pipeline-sample
spec:
  # TODO(user): Add fields here
  tasks:
    - contianer: alpine
      commands: ["sh", "-c", "good evening"]
      stage: 0
    - container: pytorch
      commands: ["ml stuff"]
      stage: 0
  taskRefs:
    - task-sample
    - 1
