apiVersion: pipelines.bramble.dev/v1alpha1
kind: Task
metadata:
  labels:
    app.kubernetes.io/name: task
    app.kubernetes.io/instance: task-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: docker-build
spec:
  image: docker
  command:
  - docker
  - build
  - -t
  - davidlynchsd/bramble
  - src/
