apiVersion: pipelines.bramble.dev/v1alpha1
kind: Task
metadata:
  labels:
    app.kubernetes.io/name: t2
    app.kubernetes.io/instance: t2
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: hello
spec:
  image: nginx
  command: ["sh", "-c", "echo good morning"]
