apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bramble-ui
  name: bramble-ui
  namespace: bramble
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bramble-ui
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bramble-ui
    spec:
      containers:
        - image: davidlynchsd/bramble-ui
          name: bramble-ui
          ports:
            - containerPort: 5555
              protocol: TCP
      serviceAccountName: bramble-ui-sa
