apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ui
  name: ui
  namespace: bramble
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ui
    spec:
      containers:
        - image: davidlynchsd/bramble-ui
          name: bramble-ui
          ports:
            - containerPort: 5555
              protocol: TCP
          env:
            - name: IN_CLUSTER
              value: "1"
      serviceAccountName: ui-sa
